version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phonebook
    ports: ["5432:5432"]
    volumes: [pg:/var/lib/postgresql/data]
volumes:
  pg: {}